// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsE9e9h5DV_AVfdJOa4amr1odbu6wj0O4',
    appId: '1:628590247798:web:936faaf1a4fe6326734457',
    messagingSenderId: '628590247798',
    projectId: 'cwnu-club',
    authDomain: 'cwnu-club.firebaseapp.com',
    storageBucket: 'cwnu-club.appspot.com',
    measurementId: 'G-EQXDFWW024',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYWs5GoQ5LbrOLoKt_wabSfGfbMniWQe8',
    appId: '1:628590247798:android:bc27a64476cbce5a734457',
    messagingSenderId: '628590247798',
    projectId: 'cwnu-club',
    storageBucket: 'cwnu-club.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBALLMc_JYnf52x8Iv4q_2NQgvjdGl0HFw',
    appId: '1:628590247798:ios:3f66649a90021fa8734457',
    messagingSenderId: '628590247798',
    projectId: 'cwnu-club',
    storageBucket: 'cwnu-club.appspot.com',
    androidClientId: '628590247798-ahb9e0t9m6r6jdagpv9l1bn4nvm5sg7c.apps.googleusercontent.com',
    iosClientId: '628590247798-12se4qohmkrsto81fvo3t4ihh7jhu1nk.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwnuClubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBALLMc_JYnf52x8Iv4q_2NQgvjdGl0HFw',
    appId: '1:628590247798:ios:3f66649a90021fa8734457',
    messagingSenderId: '628590247798',
    projectId: 'cwnu-club',
    storageBucket: 'cwnu-club.appspot.com',
    androidClientId: '628590247798-ahb9e0t9m6r6jdagpv9l1bn4nvm5sg7c.apps.googleusercontent.com',
    iosClientId: '628590247798-12se4qohmkrsto81fvo3t4ihh7jhu1nk.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwnuClubApp',
  );
}
